[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = 'Brought to you by <a class="text-muted" href="https://gethyas.com/">Hyas</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'

[es]
  languageName = "Spanish"
  contentDir = "content/es"
  weight = 10
  [es.params]
    languageISO = "ES"
    languageTag = "es-CL"
    footer = 'Desarrollado por <a class="text-muted" href="https://clcert.cl/">CLCERT</a>'
    alertText = '<a class="alert-link stretched-link fw-normal" href="/blog/example-post/">Doks version 1.0 just shipped!</a>'
